/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        title: 'var(--color-title)',
        liseret: 'var(--color-liseret)',
        accent: 'var(--color-accent)',
        accentDark: 'var(--color-accent-dark)',
        onAccent: 'var(--color-on-accent)',
        body: 'var(--color-body)',
        muted: 'var(--color-muted)',
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
      },
      fontFamily: {
        display: ['"Hanken Grotesk"', 'sans-serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"Spline Sans Mono"', 'monospace'],
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.875rem',
      },
      spacing: {
        xs: '0.5rem',
        sm: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '5rem',
        '3xl': '8rem',
      },
      borderRadius: {
        sm: '4px',
        md: '10px',
        lg: '14px',
        card: '14px',
        button: '10px',
        section: '32px',
      },
    },
  },
  plugins: [],
};
